name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  checks:
    name: Project Checks
    runs-on: ${{ matrix.os }}
    timeout-minutes: 5

    strategy:
      matrix:
        go-version: [1.20.x]
        os: [ubuntu-22.04]

    steps:
      - uses: actions/setup-go@v3
        with:
          go-version: ${{ matrix.go-version }}

      - name: Set env
        shell: bash
        run: |
          echo "GOPATH=${{ github.workspace }}" >> $GITHUB_ENV
          echo "${{ github.workspace }}/bin" >> $GITHUB_PATH

      - uses: actions/checkout@v3
        with:
          path: src/github.com/containerd/go-runc
          fetch-depth: 25

      - uses: containerd/project-checks@d7751f3c375b8fe4a84c02a068184ee4c1f59bc4 # v1.2.2
        with:
          working-directory: src/github.com/containerd/go-runc

  linters:
    name: Linters
    runs-on: ${{ matrix.os }}
    timeout-minutes: 10

    strategy:
      matrix:
        go-version: [1.20.x]
        os: [ubuntu-22.04]

    steps:
      - uses: actions/setup-go@v3
        with:
          go-version: ${{ matrix.go-version }}

      - uses: actions/checkout@v3
        with:
          path: src/github.com/containerd/go-runc

      - name: Set env
        shell: bash
        run: |
          echo "GOPATH=${{ github.workspace }}" >> $GITHUB_ENV
          echo "${{ github.workspace }}/bin" >> $GITHUB_PATH

      - uses: golangci/golangci-lint-action@v3
        with:
          version: v1.51.1
          working-directory: src/github.com/containerd/go-runc
          args: --timeout=5m

  tests:
    name: Tests
    runs-on: ${{ matrix.os }}
    timeout-minutes: 5

    strategy:
      matrix:
        go-version: [1.18.x, 1.19.x, 1.20.x]
        os: [ubuntu-22.04]

    steps:
      - uses: actions/checkout@v3
        with:
          path: src/github.com/containerd/go-runc

      - uses: actions/setup-go@v3
        with:
          go-version: ${{ matrix.go-version }}

      - name: Set env
        shell: bash
        run: |
          echo "GOPATH=${{ github.workspace }}" >> $GITHUB_ENV
          echo "${{ github.workspace }}/bin" >> $GITHUB_PATH

      - run: |
          go test -v -race -covermode=atomic -coverprofile=coverage.txt ./...
          bash <(curl -s https://codecov.io/bash)
        working-directory: src/github.com/containerd/go-runc
